# Use the official Python image from the Docker Hub
FROM python:3.9-slim


# Set the working directory inside the container
WORKDIR /app

# Copy the requirements.txt file first to leverage Docker cache
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire application code to the container
COPY . .

# Expose the port that the app runs on
EXPOSE 5001

# Command to run the Flask app
CMD ["python", "app.py"]
